version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    container_name: manetabi_db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: fuuma
      POSTGRES_PASSWORD: fuuma
      POSTGRES_DB: manetabi_db
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - lesson
networks:
  lesson:
