version: "3.8"
services:
  dev-postgres:
    image: mysql:8
    container_name: manetabi_db
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manetabi_db
      MYSQL_USER: fuuma
      MYSQL_PASSWORD: password
      LANG: C.utf8
      LC_ALL: C.utf8
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    restart: always
    networks:
      - lesson
networks:
  lesson:
